### ISSUE TITLE
Windows Updates hang with Cumulative Updates

### ISSUE THREAD

**Issue by JanWaller** [rgl/packer-provisioner-windows-update#30]
When using packer to create Windows images with this update plugin, it always hangs when downloading the update.
If I log onto the system, I can see in the log files of this plugin, that the update is afterwards also installed, but the reboot is never executed. A manual reboot is not registered within packer (similar to the installation itself). This only seems to happen with the big cumulative updates.

My plugin call is simply:
"provisioners": [
    { "type": "windows-update" },
]

==> alicloud-ecs: Connected to WinRM!
==> alicloud-ecs: Uploading the Windows update elevated script...
==> alicloud-ecs: Uploading the Windows update check for reboot required elevated script...
==> alicloud-ecs: Uploading the Windows update script...
==> alicloud-ecs: Running Windows update...
    alicloud-ecs: Searching for Windows updates...
    alicloud-ecs: Found Windows update (2019-01-08; 1388.13 MB): 2019-01 Cumulative Update for Windows Server 2016 for x64-based Systems (KB4480961)
    alicloud-ecs: Downloading Windows updates (1 updates; 1388.13 MB)...

**Comment by hakabo** [comment]
Did you manage to resolve this? 
I experience the same, if the cumulative is skipped it all goes through fine. No known network issues involved. 
Win version : Win2016 Datacenter

**Comment by JanWaller** [comment]
Still not fixed for us

**Comment by JanWaller** [comment]
I spent some time debugging this and found a fix.
The problem seems to be some kind of timeout. The downloads and updates take a very long time and if there is no data transfer to packer in this time, some part of the connection seems to get lost (on the server everything still executes, but packer does not receive it).

The fix is simple: send a message to display to packer every few seconds (or minutes).
see attached patch file


[packerWindowsUpdateTimeout.txt](https://github.com/rgl/packer-provisioner-windows-update/files/2893420/packerWindowsUpdateTimeout.txt)

**Comment by hakabo** [comment]
Thanks for the update @JanWaller  . I'll have to give that a try.

**Comment by hakabo** [comment]
Unfortunately, my lack of go development experience has me stumped on how to recompile the suggested update by @JanWaller . 

('make' doesn't run. 'go build' does stuff until  update\assets.go:8:12: undefined: assets)

Any dummies guides on compiling plugins for packer on Windows? :)

Additionally, the suggestion of some output on screen sounds like a good idea to prevent timeouts. Any chance you'll roll this into an update @rgl 

Appreciate the help.

**Comment by rgl** [comment]
@hakabo the master version should now compile fine out-of-box. just make sure you have the required tools (e.g. on windows you'll need msys2+go1.12+make or a WSL Ubuntu+go1.12+make)

@JanWaller Thanks for the finding! I was never able to reproduce this behavior, but I will try the suggested patch (with a minor change, I will filter the keep-alike kind of messages from showing up in normal packer output, as they will be alot of them for no useful purpose).

**Comment by hakabo** [comment]
@rgl  thanks for the tips. I was able to compile the plugin successfully after installing msys2 and see the on screen updates during the do/while loop.

Unfortunately, it didn't solve the problem for me as it continued to loop at that point for over 9 hours before I gave up. If I skip the large cumulative update, then there are no issues.

**Comment by rgl** [comment]
@hakabo did you apply the @JanWaller packerWindowsUpdateTimeout.txt patch?

**Comment by hakabo** [comment]
@rgl yes, I recompiled the plugin with the patch - I saw the still waiting for updates text. I let this run for about 9 hours. As mentioned, if I exclude the cumulative update, this works fine.
Happy to help troubleshoot.

**Comment by TaylorAsh1** [comment]
I am also facing this same issue. I have recompiled as the previous post states but am having no luck working past this issue. I'm working with server 2016. The first set of patches install without issues including:

2018-05 Cumulative Update for Windows Server 2016 for x64-based Systems

When installing this months latest Cumulative Update i cant get past downloading the update.

**Comment by rgl** [comment]
I have no clue about what is happening... Maybe connect to the machine and see the logs. 

Maybe you can try https://github.com/rgl/packer-provisioner-windows-update/pull/33 and let us know how it goes.

**Comment by Phaeilo** [comment]
I was experiencing this problem on Windows 10 LTSC Enterprise Evaluation. Applying #33 solved the problem for me.

**Comment by sithmein** [comment]
Same problem here (using Windows 10 Enterprise 18.09 ISO). The changes proposed in #33 also solved it for me. Any estimate when they will be applied to master?

**Comment by rgl** [comment]
Sorry for the delay... its at https://github.com/rgl/packer-provisioner-windows-update/releases/tag/v0.7.0

**Comment by JanWaller** [comment]
I have with the newest version without regular printing of some output (see my patch) still the problem, that packer somehow looses the connection. So, on the server everything continues to work, but packer no longer gets any feedback and waits forever. If I use my patched version, everything works as expected.

**Comment by rgl** [comment]
@JanWaller sorry for the delay... I finally got to do it in https://github.com/rgl/packer-provisioner-windows-update/commit/9aadb7bbc827701334fbc1a8cfacdcea8dc2e57b. Can you please try with the latest built version from https://ci.appveyor.com/project/rgl/packer-provisioner-windows-update/build/artifacts and let me known how it goes?

**Comment by JanWaller** [comment]
@rgl Yes, the linked build version works fine!

**Comment by rgl** [comment]
Thanks! I've released https://github.com/rgl/packer-provisioner-windows-update/releases/tag/v0.7.1

**Comment by hakabo** [comment]
Unfortunately for me, the additional output from the plugin hasn't resolved the issue. If I skip the big updates, I can successfully create a patched image. If I do not skip, then, with this current update, i just get the system performance statistics for hours. So basically, no change for me.

Any ideas? Happy to help troubleshoot. (I'm using Azure + Windows 2016 images).

**Comment by aaronk1** [comment]
@hakabo I've been waiting on the 2019-07 Cumulative Update for Windows 2016 for over 3 hours now.  I believe 0.7.1 release doesn't solve the issue for me either.

@rgl should this issue be re-opened?
@JanWaller did you test with Windows 2016 or Windows 2019 (or both)?

Seems to be doing something:
vmware-iso: Waiting for operation to complete (system performance: 93 % cpu; 60 % memory)...

**Comment by hakabo** [comment]
I've recently build win2016 datacenter and server core with no issues.

**Comment by aaronk1** [comment]
How long did the latest Cumulative Update take @hakabo ?  I'm over 4 hours now for just that one update.

**Comment by rgl** [comment]
It really can take a lot of time to update, more-so depending on how old is your base/current image.

At least its a good sign that you still see that "Waiting for operation to complete" message, it means things are still running, as you can see by the cpu and memory usages. To troubleshoot, you need to login into the machine and inspect the logs (event viewer and windows update logs). Or manually do the update using the regular windows update ui to see if that also happens.

**Comment by aaronk1** [comment]
I was able to fix this by the following sequence:

-  Boot machine from ISO with autounattend.xml
- Install VMware Tools to finalize driver installs
- Install Windows Updates (3x in a row to ensure latest Cumulative installed)
- Perform other tasks

The difference was moving Windows Updates to almost the beginning of the process in my case.
